### ISSUE TITLE
Brightness Slider

### ISSUE THREAD

**Issue by SuperLeiyan** [crdroidandroid/android_device_xiaomi_raphael#2]
Brightness slider curve seems to be missing some tunings; the first 90% barely increases any brightness while the last 10% spikes to the max.

I find myself maxing out the brightness to make my device usable under any kind of ambient lighting which is undesirable.

**Comment by firebird11** [comment]
there could be some extra steps in it, can you contact me on telegram ?

**Comment by SuperLeiyan** [comment]
> there could be some extra steps in it, can you contact me on telegram ?

I've messaged you on telegram.
